server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/bookkeeping?autoReconnect=true&characterEncoding=UTF8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 50

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

springdoc:
  server:
    url: http://localhost:8080
  swagger-ui:
    path: /api/swagger
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

decorator:
  datasource:
    p6spy:
      enable-logging: true
