server:
  error:
    whitelabel:
      enabled: false

spring:
  config:
    import:
      - aws-parameterstore:/mour/secret_prod/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 50

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET}

  web:
    resources:
      add-mappings: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 604800

springdoc:
  server:
    url: https://dnd.ac
  swagger-ui:
    enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: false

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

logging:
  config: classpath:logback/logback-prod.xml
