server:
  tomcat:
    mbeanregistry:
      enabled: true
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/mur?autoReconnect=true&characterEncoding=UTF8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 50

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
      password: mur

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: mur-upload
      credentials:
        profile:
          name: dnd

  web:
    resources:
      add-mappings: false

jwt:
  secret-key: 5765a2b9c7cb01f6d1225d8d597c16b35278ff621ab77353b6633b9bc2237834
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 604800

springdoc:
  server:
    url: http://localhost:8080
  swagger-ui:
    path: /api/swagger
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

decorator:
  datasource:
    p6spy:
      enable-logging: true

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:slack-webhook-url}

sentry:
  dsn: ${SENTRY_DSN:sentry-dsn}
  enable-tracing: true
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483647

logging:
  config: classpath:logback/logback-local.xml
