version: "3"
services:
  database: # mysql -u root -p -> 1234
    image: mysql:8.0.33
    container_name: database
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "bookkeeping"
      TZ: "Asia/Seoul"
      LANG: "C.UTF_8"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

  redis: # redis-cli
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data/data:/data"
    command: redis-server --requirepass bookkeeping --port 6379
