positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push # 로그를 Push할 Loki 서버 (Monitoring)

scrape_configs:
  - job_name: application-logging
    static_configs:
      - targets:
          - localhost # 로그를 Scrapping할 타켓 주소 (localhost)
        labels:
          job: logs
          __path__: /logs/*.log # WAS 로그파일 (Host - Docker Volume)
