CREATE TABLE IF NOT EXISTS member
(
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    email            VARCHAR(200) NULL UNIQUE,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
